services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: mascotas
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
